### ISSUE TITLE
new release tag

### ISSUE THREAD

**Issue by DavidBadura** [eymengunay/EoAirbrakeBundle#15]
Hey,

can you create a new release? Currently we are hanging on dev-master.

Thanks!

**Comment by eymengunay** [comment]
Hi @DavidBadura ,

I have just created [v1.0.5](https://github.com/eymengunay/EoAirbrakeBundle/releases/tag/v1.0.5). Thanks for the heads up!

**Comment by DavidBadura** [comment]
amazing! thx!
