### ISSUE TITLE
Not working with Twig 2

### ISSUE THREAD

**Issue by datort** [eymengunay/EoAirbrakeBundle#17]
Hey there, 

we're using your Bundle quite heavily but ran into trouble recently: One of our projects runs with PHP7 and  Symfony 3.2 which brings Twig in Version 2.3.x. Unfortunately this Bundle uses some deprecated Twig classes like Twig_Function_Method() in the NotifierExtension which have been removed with Twig 2. With these missing the Bundle won't work. 

Will there be any update soon to resolve this issue? 

Thanks!

**Comment by eymengunay** [comment]
Hello @datort ,

I'm not using this bundle actively anymore so unfortunately I don't have enough time to do the necessary update. I'd be happy to accept any pull requests regarding this issue.

Thank you for your understanding
